// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZD9CmUKKGv4UPEEhk9s1SqcKd-p7EfWE',
    appId: '1:182026520403:web:7880e303549a39076603a6',
    messagingSenderId: '182026520403',
    projectId: 'noteapp-914eb',
    authDomain: 'noteapp-914eb.firebaseapp.com',
    storageBucket: 'noteapp-914eb.firebasestorage.app',
    measurementId: 'G-WWGSFC594J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_lXaOy1Lol_wW7w4VCRPYOqQD_-zNlI',
    appId: '1:182026520403:android:72873e08a769c7366603a6',
    messagingSenderId: '182026520403',
    projectId: 'noteapp-914eb',
    storageBucket: 'noteapp-914eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjda9isaWZBX2E2rnoRd04t9JiQPHH4rI',
    appId: '1:182026520403:ios:1f24baff0eef3f626603a6',
    messagingSenderId: '182026520403',
    projectId: 'noteapp-914eb',
    storageBucket: 'noteapp-914eb.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjda9isaWZBX2E2rnoRd04t9JiQPHH4rI',
    appId: '1:182026520403:ios:1f24baff0eef3f626603a6',
    messagingSenderId: '182026520403',
    projectId: 'noteapp-914eb',
    storageBucket: 'noteapp-914eb.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZD9CmUKKGv4UPEEhk9s1SqcKd-p7EfWE',
    appId: '1:182026520403:web:ee6f6a7225a57ea56603a6',
    messagingSenderId: '182026520403',
    projectId: 'noteapp-914eb',
    authDomain: 'noteapp-914eb.firebaseapp.com',
    storageBucket: 'noteapp-914eb.firebasestorage.app',
    measurementId: 'G-37HHE0B8NH',
  );

}